In [1]:
"""
Task 1:
Create 3D array having two rows and two columns and 10
parallel
"""

import numpy as np

array =[[[1,1], [1,1]] , [[1,1], [1,1]] ,[[1,1], [1,1]],[[1,1], [1,1]],[[1,1],
[1,1]],[[1,1], [1,1],],[[1,1], [1,1]],[[1,1], [1,1]],[[1,1], [1,1]]]
print(array)
print("Result of List Method")
array = np.array(array)
print(array)

print("Result of Zeros Method")
array1 = np.zeros((10,2,2))
print(array1)

print("Result of Ones Method")
array2 = np.ones((10,2,2))
print(array2)

print("Result of Empty Method")
array3 = np.empty((10,2,2))
print(array3)

print("Result of Rshaping of Array")
array3.reshape((8,5))
print(array3)

[[[1, 1], [1, 1]], [[1, 1], [1, 1]], [[1, 1], [1, 1]], [[1, 1], [1, 1]], [[1, 1], [1, 1]], [[1, 1], [1, 1]], [[1, 1], [1, 1]], [[1, 1], [1, 1]], [[1, 1], [1, 1]]]
Result of List Method
[[[1 1]
  [1 1]]

 [[1 1]
  [1 1]]

 [[1 1]
  [1 1]]

 [[1 1]
  [1 1]]

 [[1 1]
  [1 1]]

 [[1 1]
  [1 1]]

 [[1 1]
  [1 1]]

 [[1 1]
  [1 1]]

 [[1 1]
  [1 1]]]
Result of Zeros Method
[[[0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]]]
Result of Ones Method
[[[1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]]]
Result of Empty Method
[[[1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]]

 [[1. 1.]
  [

In [2]:
"""
Task 2
Convert a 4D Numpy array having 24 elements into a 2D array
having square of each element.
"""

array4D = np.ones((1,4,2,3))
array4D[:,:,0:] = 3
array4D = array4D**2
print("The 4D numpy array")
print(array4D)
array2D = array4D.reshape(4,6)
print("The 2D numpy array")
print(array2D) 


The 4D numpy array
[[[[9. 9. 9.]
   [9. 9. 9.]]

  [[9. 9. 9.]
   [9. 9. 9.]]

  [[9. 9. 9.]
   [9. 9. 9.]]

  [[9. 9. 9.]
   [9. 9. 9.]]]]
The 2D numpy array
[[9. 9. 9. 9. 9. 9.]
 [9. 9. 9. 9. 9. 9.]
 [9. 9. 9. 9. 9. 9.]
 [9. 9. 9. 9. 9. 9.]]


In [3]:
"""
Task 3
Make a list of 1000 elements between 0 and 1. Calculate square
of each element and print time taken for execution. Repeat it for
Numpy and compare time. Increase elements up to 10000 and 1000000
and see results.
"""

import random
import numpy as np
# Using Numpy Array
array = np.random.rand(1000)
print(array)
print("Square of elelements of Array is :" )
%time array2 = [x**2 for x in array]
print(array2)
# Using List
array = [random.random() for _ in range(1000)]
%time array2 = [x**2 for x in array]

[0.00396514 0.96104929 0.26780244 0.43993804 0.25106311 0.58932203
 0.53323729 0.69202371 0.57240187 0.66856376 0.11772618 0.4456923
 0.5922795  0.18408406 0.91741669 0.53090608 0.3187873  0.10356338
 0.19553866 0.21259213 0.32893874 0.33838958 0.49800805 0.37451914
 0.68522528 0.94358821 0.16474999 0.4563333  0.44983465 0.96831981
 0.82539688 0.49149158 0.40541985 0.22260935 0.7610539  0.22986022
 0.6756437  0.95056203 0.40933098 0.84348275 0.84016989 0.37287788
 0.9996382  0.31626484 0.76124624 0.27878946 0.48251852 0.14911006
 0.94984305 0.42906643 0.52669496 0.95678885 0.36744386 0.79156293
 0.2537127  0.93615377 0.54854128 0.32655391 0.35601582 0.84971173
 0.66389205 0.88171292 0.51047907 0.57725106 0.81875368 0.96329261
 0.73986947 0.38548158 0.56924561 0.15897888 0.46539867 0.0642868
 0.27223791 0.58489204 0.85548268 0.80131278 0.94059511 0.12104999
 0.6306828  0.69837504 0.96480585 0.65651228 0.36078502 0.61723614
 0.22631204 0.10966835 0.00116329 0.56838361 0.80270549 0.934922

In [6]:
"""
Task 4
Make a Numpy array having 5 rows and 5 columns using ones()
function.
After that convert it into the following shape:
[[1., 1., 1., 1., 1.],
[1., 0., 0., 0., 1.],
[1., 0., 0., 0., 1.],
[1., 0., 0., 0., 1.],
[1., 1., 1., 1., 1.]]
"""

array = np.ones((5,5))
array[1:4,1:4] = 0
print(array)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]
