In [2]:
import numpy as np

In [3]:
"""
Task 1.
Create a 3x3 matrix with values ranging from 0 to 8
"""
matrix = np.arange(0,9)
matrix = matrix.reshape(3,3)
print(matrix) 

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [4]:
"""
Task 2.
Create a 3x3 matrix where the diagonal elements are [1, 2, 3] and the offdiagonal elements are zeros.
"""
matrix = np.zeros((3,3))
for i in range(0,3):
    matrix[i,i] = i+1
print(matrix) 

[[1. 0. 0.]
 [0. 2. 0.]
 [0. 0. 3.]]


In [6]:
"""
Task 3.
Find the mean, median, and standard deviation of an array [1, 2, 3, 4, 5].
"""
array = np.arange(1,6)
print("Array : ",array)
mean = np.mean(array)
print("Mean : ", mean)
median = np.median(array)
print("Median : ", median)
std = np.std(array)
print("Std : ", std) 


Array :  [1 2 3 4 5]
Mean :  3.0
Median :  3.0
Std :  1.4142135623730951


In [7]:
"""
Task 4
.Given two arrays A = [1, 2, 3] and B = [4, 5, 6], concatenate them into a single array.
"""
A = np.array([1, 2, 3])
B = np.array([4, 5, 6])
C = np.concatenate([A, B])
print("C : ", C) 


C :  [1 2 3 4 5 6]


In [8]:
"""
Task 5.
Find the dot product of two matrices: A = [[1, 2], [3, 4]] and B = [[5, 6], [7, 8]].
"""

A = np.array([[1, 2],[3, 4]])
print("Matrix A :\n")
print(A)
print()
B = np.array([[5, 6],[7, 8]])
print("Matrix B :\n")
print(B)
print()
DotProduct = np.dot(A, B)
print("Dot Product of A and B :\n")
print(DotProduct)
print() 

Matrix A :

[[1 2]
 [3 4]]

Matrix B :

[[5 6]
 [7 8]]

Dot Product of A and B :

[[19 22]
 [43 50]]



In [9]:
"""
Task 6
.Given an array [1, 2, 3, 4, 5], replace all even numbers with zeros.
"""

array = np.arange(1,6)
print("Original Numpy Array : ", array)
print()
array[array%2 == 0] = 0
print("Replaced Array : ", array)

Original Numpy Array :  [1 2 3 4 5]

Replaced Array :  [1 0 3 0 5]


In [10]:
"""
Task 7
Given a matrix [[1, 2, 3], [4, 5, 6], [7, 8, 9]], calculate the sum of each column.
"""

array = np.arange(1,10)
array = array.reshape(3,3)
print("Original Matrix : ")
print(array)
print()
SumArray = np.sum(array, axis = 0)
print("Column wise sum of Matrix is : ")
print(SumArray)

Original Matrix : 
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Column wise sum of Matrix is : 
[12 15 18]


In [11]:
"""
Task 8
Write a function that takes two arrays A and B, and returns the indices where
the elements of A are greater than the corresponding elements of B.
"""

def LargestIndex(array1, array2):
    array3 = np.where(array1 > array2)
    return array3
array1 = np.array([10, 4, 23, -100, 200, 789, 4000, 0, 1, 555])
array2 = np.array([-10, 40, 23, -200, 2000, 788, 2000, 0, 100, 524])
print("The indeces of A with greater value than B are : ")
index = LargestIndex(array1,array2)
print (index) 


The indeces of A with greater value than B are : 
(array([0, 3, 5, 6, 9], dtype=int64),)


In [14]:
"""
Task 9
Given a 2D array, calculate the sum of the diagonal elements that are divisible
by 3.
"""

matrix = np.arange(1, 10)
matrix = matrix.reshape(3,3)
print(matrix)
matrix = np.diag(matrix)
DiagonalSum = sum(matrix[matrix%2 !=0])
print("\nThe sum of diagonal that are divisible by 3 is : ",DiagonalSum) 

[[1 2 3]
 [4 5 6]
 [7 8 9]]

The sum of diagonal that are divisible by 3 is :  15


In [20]:
"""
Task 10.
Create a function that takes a 2D array and returns the row with the maximum
sum of its elements.
"""

def max_sum_row(array):
    Rowsum = np.sum(array, axis=1)
    MaxSumIndex =np.argmax(Rowsum)
    return array[MaxSumIndex]
array=np.array([[4,56,20,10],[80,7,6,5]])
print("The matrix is : \n")
print(array)
print("\nThe row of matrix with maximum sum is : ",max_sum_row(array))   

The matrix is : 

[[ 4 56 20 10]
 [80  7  6  5]]

The row of matrix with maximum sum is :  [80  7  6  5]


In [21]:
"""
Task 11.
Generate a random 5x5 matrix and replace all negative values with zeros, while
keeping the positive values intact.
"""

matrix = np.random.randint(-5,5,(5,5))
print("Original Matrix")
print(matrix)
matrix[matrix<0]= 0
print("\nChanged Matrix")
print(matrix) 


Original Matrix
[[ 2 -1 -2 -5  2]
 [ 4 -5 -4  0 -4]
 [-3  2 -5  4 -2]
 [-1 -2 -5 -5  2]
 [ 3 -2 -2 -3 -3]]

Changed Matrix
[[2 0 0 0 2]
 [4 0 0 0 0]
 [0 2 0 4 0]
 [0 0 0 0 2]
 [3 0 0 0 0]]


In [22]:
"""
Task 12.
Given a 1D array, calculate the moving average over a window of size 3. The
mov-ing average at index i is the average of elements at indices i-1, i, and i+1.
"""

array1=np.arange(1,11)
end =3
array2=np.array([])
for i in range(0,8):
    result = sum(array1[i:end])
    i+=1
    end+=1
    array2=np.append(array2,result)
print(array2) 


[ 6.  9. 12. 15. 18. 21. 24. 27.]


In [23]:
"""
Task 13.
Implement the Euclidean distance function that takes two arrays as inputs and
re-turns the Euclidean distance between them.
"""

def Euclidean_Distance(array1,array2):
    difference = array1-array2
    squared_difference=np.square(difference)
    sum_squared_difference=np.sum(squared_difference, axis=-1)
    distance=np.sqrt(sum_squared_difference)
    return distance
array1=np.array([12,3,20])
array2=np.array([40,55,65])
print("euclidean distance is", Euclidean_Distance(array1,array2)) 

euclidean distance is 74.24957912338628


In [24]:
"""
Task 14:
Create a function that takes an array and returns a new array with the
elements normalized between 0 and 1.
"""

def normalize(array):
    arr_min=np.min(array)
    arr_max=np.max(array)
    normalized_arr= (array - arr_min)/ (arr_max - arr_min)
    return normalized_arr
array = np.array([10,20,30,40,50])
normalized_array = normalize(array)
print("Normalized array is", normalized_array) 

Normalized array is [0.   0.25 0.5  0.75 1.  ]
